theme: jekyll-theme-cayman
title: Tim's Blog
description: Read about my adventures in software.

avatar: https://avatars0.githubusercontent.com/u/15240347

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: becktimd@gmail.com
  facebook:
  flickr:
  github: door-bell
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: # username, no @
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-151817999-1